# Configuration parameters for running an LMR reconstruction.  See LMR_config
# for a description of each parameter.  Here we provide a default setting as an
# example, not a best-use scenario.
#
# The 'null' value resolves to a default path pattern (using lmr_path) for all
# directory parameters.  For other parameters 'null' signifies the parameter is
# not used. This is python-interpreted as None. 
wrapper:
  iter_range:  !!python/tuple [0, 19] 
  param_search: null
  multi_seed: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

core:
  nexp: test_recon_cool_season_500hpa_hgt
  lmr_path: /Users/jjyan/Desktop/NA_reconstrution/code/PDA/data 

  datadir_output: //Users/jjyan/Desktop/NA_reconstrution/code/PDA/output/wrk 
  archive_dir: /Users/jjyan/Desktop/NA_reconstrution/code/PDA/output 
  online_reconstruction: False
  clean_start: True
  use_precalc_ye: True
  write_posterior_Ye: False
  recon_period: !!python/tuple [800, 2000] 
  recon_timescale: 1
  anom_reference_period: !!python/tuple [1951, 1980]
  nens: 200 
  seed: null
  loc_rad: 25000

  # Ensemble archiving options: ens_full, ens_variance, ens_percentiles, ens_subsample
  save_archive: ens_variance
  save_archive_percentiles: !!python/tuple [5, 95]
  save_archive_ens_subsample: 10
  # Possible regridding reanalysis 2D fields
  archive_regrid_method: null
  archive_esmpy_interp_method: bilinear
  archive_esmpy_regrid_to: t42

proxies:
  use_from: [LMRdb]
  proxy_frac: 1.0
  proxy_timeseries_kind: asis
  proxy_availability_filter: False
  proxy_availability_fraction: 1.0

     
  LMRdb:
    dbversion: 'v1.0.0'
    datadir_proxy: null
    datafile_proxy: 'LMRdb_{}_Proxies.df.pckl'
    metafile_proxy: 'LMRdb_{}_Metadata.df.pckl'
    dataformat_proxy: 'DF'
    regions: [
      'Antarctica',
      'Arctic',
      'Asia',
      'Australasia',
      'Europe',
      'North America',
      'South America'
      ]
    proxy_resolution: [1.0]
    NA_zoom: []
    database_filter: [
#     'PAGES2kv2',
#     'LMR'
      ]
    #proxy_blacklist: [ ]
    proxy_blacklist: ["Warm Season Tree Rings","Tree Rings"]
    proxy_order: [
      'Tree Rings_WidthPages2',
      'Tree Rings_WidthBreit',
      'Tree Rings_WoodDensity',
      'Tree Rings_Isotopes',
      'Corals and Sclerosponges_d18O',
      'Corals and Sclerosponges_SrCa',
      'Corals and Sclerosponges_Rates',
      'Ice Cores_d18O',
      'Ice Cores_dD',
      'Ice Cores_Accumulation',
      'Ice Cores_MeltFeature',
      'Lake Cores_Varve',
      'Lake Cores_BioMarkers',
      'Lake Cores_GeoChem',
      'Lake Cores_Misc',
      'Marine Cores_d18O',
#      'Speleothems_d18O',
      'Bivalve_d18O',
      'Documents', 
      'Tree Rings China', 
      'Ice Cores China',
      'Warm Season Tree Rings',
      'Cool Season Tree Rings'  
      ]
    proxy_psm_type:
      Corals and Sclerosponges_d18O:  linear
      Corals and Sclerosponges_SrCa:  linear
      Corals and Sclerosponges_Rates: linear
      Ice Cores_d18O:                 linear
      Ice Cores_dD:                   linear
      Ice Cores_Accumulation:         linear
      Ice Cores_MeltFeature:          linear
      Lake Cores_Varve:               linear
      Lake Cores_BioMarkers:          linear
      Lake Cores_GeoChem:             linear
      Lake Cores_Misc:                linear
      Marine Cores_d18O:              linear
      Tree Rings_WidthPages2:         bilinear
      Tree Rings_WidthBreit:          bilinear
      Tree Rings_WoodDensity:         bilinear
      Tree Rings_Isotopes:            bilinear
      Speleothems_d18O:               linear
      Bivalve_d18O:                   linear
      Documents:                      grade
      Tree Rings China:               bilinear
      Ice Cores China:                linear
      Warm Season Tree Rings:         bilinear
      Cool Season Tree Rings:         bilinear
    proxy_assim2:
      Corals and Sclerosponges_d18O: [
        'd18O',
        'delta18O',
        'd18o',
        'd18O_stk',
        'd18O_int',
        'd18O_norm',
        'd18o_avg',
        'd18o_ave',
        'dO18',
        'd18O_4'
        ]
      Corals and Sclerosponges_SrCa: [
        'Sr/Ca',
        'Sr_Ca',
        'Sr/Ca_norm',
        'Sr/Ca_anom',
        'Sr/Ca_int'
        ]
      Corals and Sclerosponges_Rates: [
        'ext',
        'calc',
        'calcification',
        'calcification rate',
        'composite'
        ]
      Ice Cores_d18O: [
        'd18O',
        'delta18O',
        'delta18o',
        'd18o',
        'd18o_int',
        'd18O_int',
        'd18O_norm',
        'd18o_norm',
        'dO18',
        'd18O_anom'
        ]
      Ice Cores_dD: [
        'deltaD',
        'delD',
        'dD'
        ]
      Ice Cores_Accumulation: [
        'accum',
        'accumu'
        ]
      Ice Cores_MeltFeature: ['MFP','melt']
      Lake Cores_Varve: [
        'thickness',
        'varve',
        'varve_thickness',
        'varve thickness'
        ]
      Lake Cores_BioMarkers: [
        'Uk37',
        'TEX86'
        ]
      Lake Cores_GeoChem: [
        'Sr/Ca',
        'Mg/Ca',
        'Cl_cont'
        ]
      Lake Cores_Misc: [
        'RABD660_670',
        'X_radiograph_dark_layer',
        'massacum'
        ]
      Marine Cores_d18O: ['d18O']
      Speleothems_d18O: ['d18O']
      Bivalve_d18O: ['d18O']
      Tree Rings_WidthBreit: ['trsgi_breit']
      Tree Rings_WidthPages2: ['trsgi']
      Tree Rings_WoodDensity: [
        'max_d',
        'min_d',
        'early_d',
        'earl_d',
        'density',
        'late_d',
        'MXD'
        ]
      Tree Rings_Isotopes: ['d18O']
      Documents: ['Dry_wet_index']
      Tree Rings China: ['trsgi']
      Ice Cores China: ['accum']
      Warm Season Tree Rings: ['trsgi']
      Cool Season Tree Rings: ['trsgi']


psm:
  all_calib_sources:
    temperature: [GISTEMP, MLOST, NOAAGlobalTemp, HadCRUT, BerkeleyEarth]
    moisture: [GPCC, DaiPDSI]

  calib_period: !!python/tuple [1850, 2015]
  avgPeriod: season
  season_source: psm_calib

  linear:
    datatag_calib: GISTEMP
    pre_calib_datafile: null
    psm_r_crit: 0.0


prior:
  prior_source: ccsm4_last_millenium


  state_variables:
    zg_500hPa_Amon: anom


  detrend: False

  # regridding options: null, simple, esmpy or spherical_harmonics
  regrid_method: esmpy
  # next parameter applies only to *simple* and *spherical_harmonics* options
  regrid_resolution: 42
  # specific to *esmpy*
  esmpy_interp_method: bilinear
  esmpy_regrid_to: 20CRv2grid_low

  state_variables_info:
    temperature: [
      'tas_sfc_Amon'
      ]
    moisture: [
      'pr_sfc_Amon',
      ]
