# Configuration parameters for running an LMR reconstruction.  See LMR_config
# for a description of each parameter.  Here we provide a default setting as an
# example, not a best-use scenario.
#
# The 'null' value resolves to a default path pattern (using lmr_path) for all
# directory parameters.  For other parameters 'null' signifies the parameter is
# not used. This is python-interpreted as None. 

wrapper:
  iter_range:  !!python/tuple [0, 19]  #19
  param_search: null
  multi_seed: null

core:
  nexp: test_recon_season_GPCC_WARM_prior_number
  lmr_path: /Users/jjyan/Desktop/NA_reconstrution/code/PPE/data #/home/disk/kalman3/rtardif/LMR

  datadir_output: /Users/jjyan/Desktop/NA_reconstrution/output/wrk #home/disk/kalman3/rtardif/LMR/output/wrk
  archive_dir: /Users/jjyan/Desktop/NA_reconstrution/output

  online_reconstruction: False
  clean_start: True
  use_precalc_ye: True
  write_posterior_Ye: False
  recon_period: !!python/tuple [0, 2000] #[1800, 2000]
#  recon_period: !!python/tuple [-120000, 2000]
  recon_timescale: 1
#  recon_timescale: 250
  anom_reference_period: !!python/tuple [1951, 1980]
  nens: null
  seed: null
  loc_rad: 7000

  # Ensemble archiving options: ens_full, ens_variance, ens_percentiles, ens_subsample
  save_archive: ens_variance
  save_archive_percentiles: !!python/tuple [5, 95]
  save_archive_ens_subsample: 10
  # Possible regridding reanalysis 2D fields
  archive_regrid_method: null
  archive_esmpy_interp_method: bilinear
  archive_esmpy_regrid_to: t42

proxies:
  use_from: [STR_WARM]
#  use_from: [LMRdb]
#  use_from: [NCDCdtda]  

  proxy_frac: 1.0
  proxy_timeseries_kind: asis
  proxy_availability_filter: False
  proxy_availability_fraction: 1.0

  PAGES2kv1:
    datadir_proxy: null
    datafile_proxy: Pages2kv1_Proxies.df.pckl
    metafile_proxy: Pages2kv1_Metadata.df.pckl
    dataformat_proxy: DF
    regions: [
      'Antarctica',
      'Arctic',
      'Asia',
      'Australasia',
      'Europe',
      'North America',
      'South America'
      ]
    proxy_resolution: [1.0]
    proxy_blacklist: []
    proxy_order: [
      'Tree ring_Width',
      'Tree ring_Density',
      'Ice core_d18O',
      'Ice core_d2H',
      'Ice core_Accumulation',
      'Coral_d18O',
      'Coral_Luminescence',
      'Lake sediment_All',
      'Marine sediment_All',
      'Speleothem_All'
      ]
    proxy_psm_type:
      Tree ring_Width:       linear
      Tree ring_Density:     linear
      Ice core_d18O:         linear
      Ice core_d2H:          linear
      Ice core_Accumulation: linear
      Coral_d18O:            linear
      Coral_Luminescence:    linear
      Lake sediment_All:     linear
      Marine sediment_All:   linear
      Speleothem_All:        linear
    proxy_assim2:
      Tree ring_Width: [
        'Ring width',
        'Tree ring width',
        'Total ring width',
        'TRW'
        ]
      Tree ring_Density: [
        'Maximum density',
        'Minimum density',
        'Earlywood density',
        'Latewood density',
        'MXD'
        ]
      Ice core_d18O: [ 'd18O' ]
      Ice core_d2H: [ 'd2H' ]
      Ice core_Accumulation: [ 'Accumulation' ]
      Coral_d18O: [ 'd18O' ]
      Coral_Luminescence: [ 'Luminescence' ]
      Lake sediment_All: [
        'Varve thickness',
        'Thickness',
        'Mass accumulation rate',
        'Particle-size distribution',
        'Organic matter',
        'X-ray density'
        ]
      Marine sediment_All: [ 'Mg/Ca' ]
      Speleothem_All: [ 'Lamina thickness' ]

  LMRdb:
    dbversion: 'v1.0.0'
    datadir_proxy: null
    datafile_proxy: 'LMRdb_{}_Proxies.df.pckl'
    metafile_proxy: 'LMRdb_{}_Metadata.df.pckl'
    dataformat_proxy: 'DF'
    regions: [
      'Antarctica',
      'Arctic',
      'Asia',
      'Australasia',
      'Europe',
      'North America',
      'South America'
      ]
    proxy_resolution: [1.0]
    database_filter: [
#     'PAGES2kv2',
#     'LMR'
      ]
    proxy_blacklist: []

    proxy_order: [
      'Tree Rings_WidthPages2',
      'Marine Cores_d18O',
      'Documents' 
      ]
    proxy_psm_type:
      Corals and Sclerosponges_d18O:  linear
      Tree Rings_WidthPages2:         bilinear
      Documents:                      grade
    proxy_assim2:
      Corals and Sclerosponges_d18O: [
        'd18O',
        'delta18O',
        'd18o',
        'd18O_stk',
        'd18O_int',
        'd18O_norm',
        'd18o_avg',
        'd18o_ave',
        'dO18',
        'd18O_4'
        ]
      Tree Rings_WidthPages2: ['trsgi']
      Documents: ['Dry_wet_index']


  STR_WARM:
    datadir_proxy: null
    datafile_proxy: 'Warm_season_Proxies.df.pckl'
    metafile_proxy: 'Warm_season_Metadata.df.pckl'
    dataformat_proxy: 'DF'
    regions: []
    proxy_resolution: [1.0]
    database_filter: []
    proxy_blacklist: []
    proxy_order: [
     'Seasonal Tree Rings'
     ]
    proxy_psm_type:
      Seasonal Tree Rings:     linear
    proxy_assim2:
      Seasonal Tree Rings: [
       'trsgi'
        ]


  STR_COOL:
    datadir_proxy: null
    datafile_proxy: 'Cool_season_Proxies.df.pckl'
    metafile_proxy: 'Cool_season_Metadata.df.pckl'
    dataformat_proxy: 'DF'
    regions: []
    proxy_resolution: [1.0]
    database_filter: []
    proxy_blacklist: []
    proxy_order: [
     'Seasonal Tree Rings'
     ]
    proxy_psm_type:
      Seasonal Tree Rings:     linear
    proxy_assim2:
      Seasonal Tree Rings: [
       'trsgi'
        ]


  NCDCdtda:
    dbversion: 'v0.0.1'
    datadir_proxy: null
    datafile_proxy: 'DTDA_{}_Proxies.df.pckl'
    metafile_proxy: 'DTDA_{}_Metadata.df.pckl'
    dataformat_proxy: 'DF'
    regions: []
    proxy_resolution: [!!python/tuple [0.,5000.]]
    database_filter: []
    proxy_blacklist: []
    proxy_order: [
#     'Marine Cores_uk37',
     'Marine sediments_uk37'
     ]
    proxy_psm_type:
      Marine Cores_uk37:     bayesreg_uk37
      Marine sediments_uk37: bayesreg_uk37
    proxy_assim2:
      Marine Cores_uk37: [
        'uk37',
        'UK37'
        ]
      Marine sediments_uk37: [
        'uk37',
        'UK37'
        ]
psm:
  all_calib_sources:
    temperature: [GISTEMP, MLOST, NOAAGlobalTemp, HadCRUT, BerkeleyEarth]
    moisture: [GPCC, DaiPDSI]

  calib_period: !!python/tuple [1850, 2015]
  #avgPeriod: annual
  avgPeriod: season
  season_source: proxy_metadata
  #season_source: psm_calib

  linear:
    datatag_calib: GPCC
    pre_calib_datafile: null
    psm_r_crit: 0.0

  linear_TorP:
    datatag_calib_T: GISTEMP
    datatag_calib_P: GPCC
    pre_calib_datafile_T: null
    pre_calib_datafile_P: null
    psm_r_crit: 0.0

  bilinear:
    datatag_calib_T: GISTEMP
    datatag_calib_P: GPCC
    pre_calib_datafile: null
    psm_r_crit: 0.0

  h_interp:
    radius_influence: 50.0
    datadir_obsError: ./
    filename_obsError: R.txt
    dataformat_obsError: TXT
    datafile_obsError: None

  bayesreg_uk37:
    datadir_BayesRegressionData: null
    filename_BayesRegressionData: null
    dataformat_BayesRegressionData: MAT
    
  grade:
    datatag_calib: GPCC
    pre_calib_datafile: null
    psm_r_crit: 0.0

prior:
  prior_source: ccsm4_last_millenium
#  prior_source: icesm_last_millennium
#  prior_source: ccsm3_trace21ka

  state_variables:
#    tas_sfc_Amon: anom
    pr_sfc_Amon: anom
#    PRECT_sfc_Amon: anom
#    scpdsi_sfc_Amon: anom
#    psl_sfc_Amon: anom
#    zg_500hPa_Amon: anom
#    wap_500hPa_Amon: anom
#    wap_700hPa_Amon: anom
#    wap_850hPa_Amon: anom
#    d18O_sfc_Amon: full
#    tos_sfc_Omon: anom
#    sos_sfc_Omon: anom
#    ohc_0-700m_Omon: anom
#    AMOCindex_Omon: anom
#    AMOC26Nmax_Omon: anom
#    AMOC26N1000m_Omon: anom
#    AMOC45N1000m_Omon: anom
#    ohcAtlanticNH_0-700m_Omon: anom
#    ohcAtlanticSH_0-700m_Omon: anom
#    ohcPacificNH_0-700m_Omon: anom
#    ohcPacificSH_0-700m_Omon: anom
#    ohcIndian_0-700m_Omon: anom
#    ohcSouthern_0-700m_Omon: anom
#    ohcArctic_0-700m_Omon: anom
#    tas_sfc_Adec: full
#    psl_sfc_Adec: full
#    tos_sfc_Odec: full
#    sos_sfc_Odec: full

  detrend: False

  # regridding options: null, simple, esmpy or spherical_harmonics
  regrid_method: NA_zoom
  # next parameter applies only to *simple* and *spherical_harmonics* options
  regrid_resolution: 42
  # specific to *esmpy*
  esmpy_interp_method: bilinear
  esmpy_regrid_to: 20CRv2grid

  state_variables_info:
    temperature: [
      'tas_sfc_Amon'
      ]
    moisture: [
      'pr_sfc_Amon',
      'scpdsi_sfc_Amon',
      ]
